export { PolymartSDK, PolymartSDKError } from "./client";
export type {
	SDKConfig,
	PollStatus,
	User,
	Outcome,
	Poll,
	Bet,
	UserStats,
	GetPollsParams,
	GetPollsResponse,
	GetPollResponse,
	CreatePollParams,
	CreatePollResponse,
	PlaceBetParams,
	PlaceBetResponse,
	GetUserBetsResponse,
	GetUserResponse,
	ResolvePollParams,
	ResolvePollResponse,
	ErrorResponse,
} from "./types";
